/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Get started',
      link: { type: 'doc', id: 'get-started/introduction' },
      items: [{ type: 'autogenerated', dirName: 'get-started' }],
    },
    {
      type: 'category',
      label: 'Install and setup',
      link: { type: 'doc', id: 'install-and-setup/manual' },
      items: [{ type: 'autogenerated', dirName: 'install-and-setup' }],
    },
    {
      type: 'category',
      label: 'Working with FHIR',
      link: { type: 'doc', id: 'fhir/guides/overview-of-fhir' },
      items: [
        {
          type: 'doc',
          id: 'fhir/guides/overview-of-fhir',
          label: 'Overview of FHIR',
        },
        {
          type: 'category',
          label: 'Handling FHIR Resources',
          items: [
            'fhir/guides/populating-fhir-resources',
            'fhir/guides/parsing-and-serializing',
            'fhir/guides/validation',
            'fhir/guides/building-fhir-bundles',
            'fhir/guides/profiles-and-extensions',
          ],
        },
        {
          type: 'category',
          label: 'Connecting to FHIR Repositories',
          items: [
            {
              type: 'doc',
              id: 'fhir/guides/fhir-repository-connector',
              label: 'Using FHIR Repository connector',
            },
          ],
        },
        {
          type: 'category',
          label: 'Build your own Facade',
          items: [
            {
              type: 'doc',
              id: 'fhir/guides/fhir-resource-api-template',
              label: 'Developing FHIR APIs',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Working with HL7',
      link: { type: 'doc', id: 'hl7/guides/overview' },
      items: [
        {
          type: 'doc',
          id: 'hl7/guides/overview',
          label: 'Overview of HL7v2',
        },
        {
          type: 'category',
          label: 'Handling HL7 Messages',
          items: [
            {
              type: 'doc',
              id: 'hl7/guides/populating-hl7-message',
              label: 'Populating HL7 messages',
            },
            {
              type: 'doc',
              id: 'hl7/guides/parsing-and-serializing',
              label: 'Parsing and Serializing',
            },
          ],
        },
        {
          type: 'category',
          label: 'Connecting to HL7 Servers',
          items: [
            'hl7/guides/connect-to-hl7-tcp-servers',
            'hl7/guides/connect-to-hl7-file-servers',
          ],
        },
        {
          type: 'category',
          label: 'Build your own HL7 server',
          items: [
            {
              type: 'doc',
              id: 'hl7/guides/hl7-server-listener',
              label: 'HL7 server listener',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Data Transformation',
      link: { type: 'doc', id: 'data-transformation/guides/hl7v2-fhir' },
      items: [{ type: 'autogenerated', dirName: 'data-transformation/guides' }],
    },
    {
      type: 'category',
      label: 'EMR Connectivity',
      link: { type: 'doc', id: 'emr-connectivity/guides/emr-systems-overview' },
      items: [{ type: 'autogenerated', dirName: 'emr-connectivity/guides' }],
    },
    {
      type: 'category',
      label: 'SMART on FHIR',
      link: { type: 'doc', id: 'secure-health-apis/guides/smart-on-fhir-overview' },
      items: [{ type: 'autogenerated', dirName: 'secure-health-apis/guides' }],
    },
    {
      type: 'category',
      label: 'Advanced Topics',
      link: { type: 'doc', id: 'advance-topics/guides/enable-workflow' },
      items: [{ type: 'autogenerated', dirName: 'advance-topics/guides' }],
    },
  ],
};

module.exports = sidebars;
