// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Get Started',
      link: {type: 'doc', id: 'get-started/architecture'},
      items: [
        {
          type: 'doc',
          id: 'architecture/overview',
          label: 'Architecture',
        },
        'get-started/architecture',
        'get-started/open-healthcare-quickstart',
      ],
    },
    {
      type: 'category',
      label: 'Install and Setup',
      link: {type: 'doc', id: 'install-and-setup/manual'},
      items: [{type: 'autogenerated', dirName: 'install-and-setup'}],
    },
    {
      type: 'category',
      label: 'Working with FHIR',
      link: {type: 'doc', id: 'fhir/guides/overview-of-fhir'},
      items: [
        {
          type: 'doc',
          id: 'fhir/guides/overview-of-fhir',
          label: 'Overview of FHIR',
        },
        {
          type: 'category',
          label: 'Handling FHIR Resources',
          items: [
            'fhir/guides/populating-fhir-resources',
            'fhir/guides/parsing-and-serializing',
            'fhir/guides/building-fhir-bundles',
            'fhir/guides/profiles-and-extensions',
          ],
        },
        {
          type: 'category',
          label: 'Validation',
          items: [
            'fhir/guides/validation',
            'fhir/validation/profile-validation',
            'fhir/validation/terminology-validation',
            'fhir/validation/custom-rules',
          ],
        },
        {
          type: 'category',
          label: 'Terminology',
          items: [
            'fhir/terminology/overview',
            'fhir/terminology/codesystem-operations',
            'fhir/terminology/valueset-operations',
            'fhir/terminology/conceptmap-operations',
          ],
        },
        {
          type: 'category',
          label: 'Connecting to FHIR Repositories',
          items: [
            {
              type: 'doc',
              id: 'fhir/guides/fhir-repository-connector',
              label: 'Using FHIR Connector',
            },
            'fhir/guides/bulk-data-export',
          ],
        },
        {
          type: 'category',
          label: 'Build Your Own Facade',
          items: [
            {
              type: 'doc',
              id: 'fhir/guides/fhir-resource-api-template',
              label: 'Developing FHIR APIs',
            },
            {
              type: 'category',
              label: 'Search',
              items: [
                'fhir/search/overview',
                'fhir/search/search-parameters',
                'fhir/search/advanced-search',
              ],
            },
            {
              type: 'category',
              label: 'Operations',
              items: [
                'fhir/operations/overview',
                'fhir/operations/custom-operations',
              ],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Working with HL7',
      link: {type: 'doc', id: 'hl7/guides/overview'},
      items: [
        {
          type: 'doc',
          id: 'hl7/guides/overview',
          label: 'Overview of HL7v2',
        },
        {
          type: 'category',
          label: 'Handling HL7 Messages',
          items: [
            {
              type: 'doc',
              id: 'hl7/guides/populating-hl7-message',
              label: 'Populating HL7 Messages',
            },
            {
              type: 'doc',
              id: 'hl7/guides/parsing-and-serializing',
              label: 'Parsing and Serializing',
            },
            {
              type: 'doc',
              id: 'hl7/guides/validation',
              label: 'Validation',
            },
            {
              type: 'doc',
              id: 'hl7/guides/custom-hl7-message',
              label: 'Custom HL7 Messages',
            },
          ],
        },
        {
          type: 'category',
          label: 'Connecting to HL7 Servers',
          items: [
            'hl7/guides/connect-to-hl7-tcp-servers',
            'hl7/guides/connect-to-hl7-file-servers',
          ],
        },
        {
          type: 'category',
          label: 'Build Your Own HL7 Server',
          items: [
            {
              type: 'doc',
              id: 'hl7/guides/hl7-server-listener',
              label: 'HL7 Server Listener',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Data Transformation',
      link: {type: 'doc', id: 'data-transformation/guides/hl7v2-fhir'},
      items: [{type: 'autogenerated', dirName: 'data-transformation/guides'}],
    },
    {
      type: 'category',
      label: 'EMR Connectivity',
      link: {type: 'doc', id: 'emr-connectivity/guides/emr-systems-overview'},
      items: [{type: 'autogenerated', dirName: 'emr-connectivity/guides'}],
    },
    {
      type: 'category',
      label: 'Security & SMART on FHIR',
      link: {type: 'doc', id: 'secure-health-apis/guides/smart-on-fhir-overview'},
      items: [{type: 'autogenerated', dirName: 'secure-health-apis/guides'}],
    },
    {
      type: 'category',
      label: 'Performance',
      link: {type: 'doc', id: 'performance/overview'},
      items: [{type: 'autogenerated', dirName: 'performance'}],
    },
    {
      type: 'category',
      label: 'Compliance & Standards',
      link: {type: 'doc', id: 'compliance/overview'},
      items: [{type: 'autogenerated', dirName: 'compliance'}],
    },
    {
      type: 'category',
      label: 'Advanced Topics',
      link: {type: 'doc', id: 'advance-topics/overview'},
      items: [{type: 'autogenerated', dirName: 'advance-topics'}],
    },
  ],
};

module.exports = sidebars;
